chore: trying out different docker action runners
Signed-off-by: Inmoresentum <noor.mohammad.rafee@g.bracu.ac.bd>

diff --git a/.github/workflows/front-end-build-checker.yml b/.github/workflows/front-end-build-checker.yml
--- a/.github/workflows/front-end-build-checker.yml
+++ b/.github/workflows/front-end-build-checker.yml
@@ -1,4 +1,4 @@
-name: Front-End Build
+name: Front-End Build And BackEnd Integration
 
 on:
   pull_request:
@@ -11,6 +11,26 @@ jobs:
 
     steps:
       - uses: actions/checkout@v2
+      - name: Set up Java version
+        uses: actions/setup-java@v1
+        with:
+          java-version: '17'
+      - name: Build with Maven
+        run: mvn -B clean package -DskipTests --file pom.xml
+      - name: Check if build successful
+        run: |
+          if [ "$?" -ne 0 ]; then
+            echo "::error::Build failed!"
+            exit 1
+          fi
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v1
+      #      - name: Build Docker image
+      #        run: docker build . -t backend-image
+      - name: Start backend with Docker Compose
+        run: docker-compose up -d
+      - name: Wait for backend to start
+        run: sleep 60 # adjust this value as needed
       - name: Set up Node.js
         uses: actions/setup-node@v2
         with:
